language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - npm test

before_deploy: npm run build

deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
