language: node_js
node_js:
  - '10'

addons:
  postgresql: '9.6'

services:
  - postgres

install:
  - npm i -g npm@6.4.1
  - npm ci

before_script:
  - PGPASSWORD=postgres psql -c 'create database hodlfolio;' -U postgres
  - npm run migrate

script:
  - npm test
  - npm run cypress:run:ci

before_deploy: npm run build

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
