language: node_js
node_js:
  - '12'

cache:
  directories:
    - '$HOME/.npm'

addons:
  postgresql: '9.6'
  apt:
    packages:
      - libgconf-2-4

services:
  - postgres

before_script:
  - PGPASSWORD=postgres psql -c 'create database hodlfolio;' -U postgres
  - npm run migrate

script:
  - npm test
  - npm run cypress:run:ci

before_deploy: npm run build:ci

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
