language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_a483cd4a3c1c_key -iv $encrypted_a483cd4a3c1c_iv -in .travis/travis.key.enc -out .travis/travis.key -d

script:
  - npm run build

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis.key
  - ssh-add .travis/travis.key
  - ssh-keyscan dokku.hodlfolio.org >> ~/.ssh/known_hosts
  - cp app.json dist/
  - cp package.json dist/
  - cd dist && git init
  - git add . && git commit -m "Deploy to dokku"
  - git remote add deploy dokku@dokku.hodlfolio.org:hodlfolio
  - git push dokku master --force

