language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_6c26c11f88dc_key -iv $encrypted_6c26c11f88dc_iv -in travis.key.enc -out travis.key -d

script:
  - npm run build

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis.key
  - ssh-add .travis/travis.key
  - ssh-keyscan dokku.hodlfolio.org >> ~/.ssh/known_hosts
  - cd dist && git init
  - git add . && git commit -m "Deploy to dokku"
  - git remote add deploy dokku@dokku.hodlfolio.org:hodlfolio
  - git push dokku master --force

