language: node_js
node_js:
  - '8'
cache: yarn

addons:
  postgresql: "9.6"

services:
  - postgres

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - PGPASSWORD=postgres psql -c 'create database hodlfolio;' -U postgres

script:
  - npm test
  - npm run migrate
  - npm run cypress:run:ci

before_deploy: npm run build

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
